name:  CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker compose up -d --build

    - name: load database
      run: docker exec -i apache-noobMVC php ./noob.php -itest123test --testdb

   

    - name: unit test
      run: docker exec  apache-noobMVC  ./vendor/bin/phpunit --configuration phpunit.xml